title: Robot Learning Course
description: A course for teaching robot learning
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  CourseWare: https://cw.fel.cvut.cz/b231/courses/b3b33urob/start
  BRUTE: https://cw.felk.cvut.cz/brute/student/
  GitHub: https://github.com/urob-ctu

favicon_ico: "/assets/images/favicon.ico"

color_scheme: nil

callouts_level: quiet # or loud
callouts:
  slogan:
    title: Slogan
    color: yellow
  important:
    title: Important
    color: blue
  definition:
    title: Definition
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
